- name: Configure R1
  hosts: R1
  gather_facts: no
  vars:
    router_id: 1.1.1.1
    network: 10.0.0.0/24
  tasks:
    - name: Set hostname
      ios_hostname:
        name: R1
    - name: Configure interfaces
      ios_interface:
        name: GigabitEthernet0/1
        ip_address: 10.0.0.1
        netmask: 255.255.255.0
        state: present
    - name: Configure EIGRP
      ios_eigrp:
        as_number: 1
        router_id: "{{ router_id }}"
        network:
          - "{{ network }}"
        state: present

- name: Configure R2
  hosts: R2
  gather_facts: no
  vars:
    router_id: 2.2.2.2
    network: 10.0.0.0/24
  tasks:
    - name: Set hostname
      ios_hostname:
        name: R2
    - name: Configure interfaces
      ios_interface:
        name: GigabitEthernet0/1
        ip_address: 10.0.0.2
        netmask: 255.255.255.0
        state: present
    - name: Configure EIGRP
      ios_eigrp:
        as_number: 1
        router_id: "{{ router_id }}"
        network:
          - "{{ network }}"
        state: present

